### ISSUE TITLE
TypeError: Object #<StreamFilter> has no method 'restore' at Gulp.

### ISSUE THREAD

**Issue by jfarthing84** [kasperisager/vanilla-bootstrap#178] opened 2015-08-04 14:12 UTC
When trying to build, the aforementioned error is output.

```
$ npm run build

> vanilla-bootstrap@ build /media/www/forums/themes/bootstrap
> gulp

[10:07:53] Using gulpfile /media/www/forums/themes/bootstrap/gulpfile.js
[10:07:53] Starting 'styles'...
[10:08:01] 'styles' errored after 8.59 s
[10:08:01] TypeError: Object #<StreamFilter> has no method 'restore'
    at Gulp.<anonymous> (/media/www/forums/themes/bootstrap/gulpfile.js:23:18)
    at module.exports (/media/www/forums/themes/bootstrap/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/media/www/forums/themes/bootstrap/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/media/www/forums/themes/bootstrap/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/media/www/forums/themes/bootstrap/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /media/www/forums/themes/bootstrap/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:935:3

npm ERR! Linux 3.13.0-58-generic
npm ERR! argv "node" "/usr/bin/npm" "run" "build"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! vanilla-bootstrap@ build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vanilla-bootstrap@ build script 'gulp'.
npm ERR! This is most likely a problem with the vanilla-bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls vanilla-bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/www/forums/themes/bootstrap/npm-debug.log
```

**Comment by kasperisager** [comment] 2015-08-04 15:42
Duplicate of #177.

**Closed by kasperisager** 2015-08-04 15:42 UTC
