### ISSUE TITLE
When Building I Get : Plumber found unhandled error:  Error: no writecb in Transform class

### ISSUE THREAD

**Issue by nakroube** [kasperisager/vanilla-bootstrap#181] opened 2015-10-28 16:15 UTC
When trying to Build or Watch, I get the following error;

Plumber found unhandled error:
 Error: no writecb in Transform class

Does anyone already fixed that? Thanks!

**Comment by kasperisager** [comment] 2015-10-29 11:50
I'm unable to reproduce this. Could you give me the output of `node -v && npm -v && npm list --depth=0` run from the Bootstrap for Vanilla root directory?

**Comment by kasperisager** [comment] 2016-01-24 14:15
Closing as the project won't receive further updates until the release of Bootstrap 4.

**Closed by kasperisager** 2016-01-24 14:15 UTC
