### ISSUE TITLE
Dropdown notification close itself when right click link on Firefox

### ISSUE THREAD

**Issue by chrisfebian** [kasperisager/vanilla-bootstrap#140] opened 2015-01-06 02:35 UTC
When using Firefox, dropdown notification will close itself when right click the link
However this problem is not happened on other browser

**Comment by kasperisager** [comment] 2015-01-22 19:38
Can you verify that this is specific to the Bootstrap theme?w

**Comment by 4311021x** [comment] 2015-02-01 15:10
Yes I see this issue too.

**Comment by kasperisager** [comment] 2015-02-01 15:13
Is the behaviour also observed when the default theme is used?

**Comment by 4311021x** [comment] 2015-02-01 16:59
You mean Bootstrap Standard in theme options? Yes it happens with that one as well. And it happens only when you right click on a link. It doesn't happen when you right click on normal text.

**Comment by kasperisager** [comment] 2015-02-01 17:26
I mean the Vanilla default theme. This is to check if the issue is specific to the Bootstrap theme and not Vanilla in general.

**Comment by 4311021x** [comment] 2015-02-01 18:22
Ah okay it happens with the Vanilla default theme and on vanillaforums.org as well. So I guess you're using the Vanilla way to display dropdowns and not the [Bootstrap way](http://getbootstrap.com/examples/navbar/)?

**Comment by kasperisager** [comment] 2015-02-01 18:30
Yep, all dropdowns are handled by Vanilla. Closing as a non-theme issue.

**Closed by kasperisager** 2015-02-01 18:30 UTC
