### ISSUE TITLE
Mobile theme discussions not centered

### ISSUE THREAD

**Issue by twirk** [kasperisager/vanilla-bootstrap#136] opened 2014-12-06 08:14 UTC
When posting a new discussion the post is moved to the right (ie. padding-left=20%). This makes for a cramped feel when viewing on mobile devices (im viewing on Android)

p.s.
• Vanilla 2.1.6
• Bootstrap Theme 2.3.4.

**Comment by kasperisager** [comment] 2015-01-22 19:37
Closing as duplicate of #116.

**Closed by kasperisager** 2015-01-22 19:37 UTC
