### ISSUE TITLE
Signin Popup window does not scroll on Android devices. Problematic

### ISSUE THREAD

**Issue by twirk** [kasperisager/vanilla-bootstrap#134] opened 2014-12-06 08:03 UTC
When signing in on Android phones the jquery (i think it is) popup window with the username and password textfields cannot scroll down. This means when the Android input keyboard is up you cant access the "Sign In" button.

It would be nice if the popup window was fixed to scroll with the background (meaning the main website) to access the Sign In button hidden behind Androids on screen keyboard.

Hope that makes sense!

Thanks!

p.s.
• Vanilla 2.1.6
• Bootstrap Theme 2.3.4.

**Comment by kasperisager** [comment] 2015-02-24 18:36
Duplicate of #132.

**Closed by kasperisager** 2015-02-24 18:36 UTC
