### ISSUE TITLE
The Navbar on mobile no longer works

### ISSUE THREAD

**Issue by imnotjames** [kasperisager/vanilla-bootstrap#150] opened 2015-02-04 13:57 UTC
This is a side affect of 9a4c3e353d84e388791403fcd33f0652cfaff37d

Pretty easy fix.   Will be trying to fork + open a pull request fixing the funtionality today?

**Comment by kasperisager** [comment] 2015-02-04 14:06
There's a very good reason for that change. Check out the release notes: https://github.com/kasperisager/vanilla-bootstrap/releases/tag/v2.5.0

Duplicate of #146, #145.

**Closed by kasperisager** 2015-02-04 14:06 UTC
