### ISSUE TITLE
The menu button in mobile view does not work

### ISSUE THREAD

**Issue by joseamirandavelez** [kasperisager/vanilla-bootstrap#146] opened 2015-01-29 03:12 UTC
For some reason, the menu button when browsing in my cell phone and in Chrome Dev Tools using a mobile view is not working.

website: astroforos.com

**Comment by joseamirandavelez** [comment] 2015-01-29 03:15
By the way, Im using 2.5.0

**Comment by kasperisager** [comment] 2015-01-29 07:18
Duplicate of #145. Check out the release notes for a workaround.

**Closed by kasperisager** 2015-01-29 07:18 UTC
